
package ssii2.visa.dao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VisaDAOWS", targetNamespace = "http://dao.visa.ssii2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VisaDAOWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ssii2.visa.dao.PagoBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPagos", targetNamespace = "http://dao.visa.ssii2/", className = "ssii2.visa.dao.GetPagos")
    @ResponseWrapper(localName = "getPagosResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssii2.visa.dao.GetPagosResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/getPagosRequest", output = "http://dao.visa.ssii2/VisaDAOWS/getPagosResponse")
    public List<PagoBean> getPagos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "errorLog", targetNamespace = "http://dao.visa.ssii2/", className = "ssii2.visa.dao.ErrorLog")
    @ResponseWrapper(localName = "errorLogResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssii2.visa.dao.ErrorLogResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/errorLogRequest", output = "http://dao.visa.ssii2/VisaDAOWS/errorLogResponse")
    public void errorLog(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delPagos", targetNamespace = "http://dao.visa.ssii2/", className = "ssii2.visa.dao.DelPagos")
    @ResponseWrapper(localName = "delPagosResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssii2.visa.dao.DelPagosResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/delPagosRequest", output = "http://dao.visa.ssii2/VisaDAOWS/delPagosResponse")
    public int delPagos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDebug", targetNamespace = "http://dao.visa.ssii2/", className = "ssii2.visa.dao.SetDebug")
    @ResponseWrapper(localName = "setDebugResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssii2.visa.dao.SetDebugResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/setDebugRequest", output = "http://dao.visa.ssii2/VisaDAOWS/setDebugResponse")
    public void setDebug(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
